exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: false
    permalink: /:path/

# Site title and description 
title: "analytics.muni.org | MOA Web Stats"
description: "Official data on web traffic to the Municipality of Anchorage. Published by MOA IT."

# Site's own URL
url: http://analytics.muni.org

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Departments

# Default data url
data_url: http://analytics.muni.org/data

# Default organization home url
home_url: http://www.muni.org

# Header parts
header_logo: images/200px-Seal_of_Anchorage,_Alaska_svg.png
header_host: analytics
header_domain: muni.org

# GitHub information
org_name: GSA
repo_name: analytics.usa.gov

# twitter information
twitter: mayorethananc

sass:
  sass_dir: sass
  style: nested
